interface Film {
  title: string;
  episode_id: number;
  opening_crawl: string;
  director: string;
  producer: string;
  release_date: string;
  characters: string[];
  planets: string[];
  starships: string[];
  vehicles: string[];
  species: string[];
  created: string;
  edited: string;
  url: string;
}

interface Species {
  name: string;
  classification: string;
  designation: string;
  average_height: string;
  skin_colors: string;
  hair_colors: string;
  eye_colors: string;
  average_lifespan: string;
  homeworld: string;
  language: string;
  people: string[];
  films: string[];
  created: string;
  edited: string;
  url: string;
}

interface Classification {
  name: string;
  classification: string;
}

export const mockClassifications: Classification[] = [
  {
    name: "Human",
    classification: "mammal",
  },
  {
    name: "Droid",
    classification: "artificial",
  },
  {
    name: "Yoda's species",
    classification: "mammal",
  },
  {
    name: "Neimodian",
    classification: "unknown",
  },
  {
    name: "Gungan",
    classification: "amphibian",
  },
  {
    name: "Toydarian",
    classification: "mammal",
  },
  {
    name: "Dug",
    classification: "mammal",
  },
  {
    name: "Twi'lek",
    classification: "mammals",
  },
  {
    name: "Aleena",
    classification: "reptile",
  },
  {
    name: "Vulptereen",
    classification: "unknown",
  },
  {
    name: "Xexto",
    classification: "unknown",
  },
  {
    name: "Toong",
    classification: "unknown",
  },
  {
    name: "Cerean",
    classification: "mammal",
  },
  {
    name: "Nautolan",
    classification: "amphibian",
  },
  {
    name: "Zabrak",
    classification: "mammal",
  },
  {
    name: "Tholothian",
    classification: "mammal",
  },
  {
    name: "Iktotchi",
    classification: "unknown",
  },
  {
    name: "Quermian",
    classification: "mammal",
  },
  {
    name: "Kel Dor",
    classification: "unknown",
  },
  {
    name: "Chagrian",
    classification: "amphibian",
  },
];

export const mockFilms: Film[] = [
  {
    title: "A New Hope",
    episode_id: 4,
    opening_crawl:
      "It is a period of civil war.\r\nRebel spaceships, striking\r\nfrom a hidden base, have won\r\ntheir first victory against\r\nthe evil Galactic Empire.\r\n\r\nDuring the battle, Rebel\r\nspies managed to steal secret\r\nplans to the Empire's\r\nultimate weapon, the DEATH\r\nSTAR, an armored space\r\nstation with enough power\r\nto destroy an entire planet.\r\n\r\nPursued by the Empire's\r\nsinister agents, Princess\r\nLeia races home aboard her\r\nstarship, custodian of the\r\nstolen plans that can save her\r\npeople and restore\r\nfreedom to the galaxy....",
    director: "George Lucas",
    producer: "Gary Kurtz, Rick McCallum",
    release_date: "1977-05-25",
    characters: [
      "https://swapi.dev/api/people/1/",
      "https://swapi.dev/api/people/2/",
      "https://swapi.dev/api/people/3/",
      "https://swapi.dev/api/people/4/",
      "https://swapi.dev/api/people/5/",
      "https://swapi.dev/api/people/6/",
      "https://swapi.dev/api/people/7/",
      "https://swapi.dev/api/people/8/",
      "https://swapi.dev/api/people/9/",
      "https://swapi.dev/api/people/10/",
      "https://swapi.dev/api/people/12/",
      "https://swapi.dev/api/people/13/",
      "https://swapi.dev/api/people/14/",
      "https://swapi.dev/api/people/15/",
      "https://swapi.dev/api/people/16/",
      "https://swapi.dev/api/people/18/",
      "https://swapi.dev/api/people/19/",
      "https://swapi.dev/api/people/81/",
    ],
    planets: [
      "https://swapi.dev/api/planets/1/",
      "https://swapi.dev/api/planets/2/",
      "https://swapi.dev/api/planets/3/",
    ],
    starships: [
      "https://swapi.dev/api/starships/2/",
      "https://swapi.dev/api/starships/3/",
      "https://swapi.dev/api/starships/5/",
      "https://swapi.dev/api/starships/9/",
      "https://swapi.dev/api/starships/10/",
      "https://swapi.dev/api/starships/11/",
      "https://swapi.dev/api/starships/12/",
      "https://swapi.dev/api/starships/13/",
    ],
    vehicles: [
      "https://swapi.dev/api/vehicles/4/",
      "https://swapi.dev/api/vehicles/6/",
      "https://swapi.dev/api/vehicles/7/",
      "https://swapi.dev/api/vehicles/8/",
    ],
    species: [
      "https://swapi.dev/api/species/1/",
      "https://swapi.dev/api/species/2/",
      "https://swapi.dev/api/species/3/",
      "https://swapi.dev/api/species/4/",
      "https://swapi.dev/api/species/5/",
    ],
    created: "2014-12-10T14:23:31.880000Z",
    edited: "2014-12-20T19:49:45.256000Z",
    url: "https://swapi.dev/api/films/1/",
  },
  {
    title: "The Phantom Menace",
    episode_id: 1,
    opening_crawl:
      "Turmoil has engulfed the\r\nGalactic Republic. The taxation\r\nof trade routes to outlying star\r\nsystems is in dispute.\r\n\r\nHoping to resolve the matter\r\nwith a blockade of deadly\r\nbattleships, the greedy Trade\r\nFederation has stopped all\r\nshipping to the small planet\r\nof Naboo.\r\n\r\nWhile the Congress of the\r\nRepublic endlessly debates\r\nthis alarming chain of events,\r\nthe Supreme Chancellor has\r\nsecretly dispatched two Jedi\r\nKnights, the guardians of\r\npeace and justice in the\r\ngalaxy, to settle the conflict....",
    director: "George Lucas",
    producer: "Rick McCallum",
    release_date: "1999-05-19",
    characters: [
      "https://swapi.dev/api/people/2/",
      "https://swapi.dev/api/people/3/",
      "https://swapi.dev/api/people/10/",
      "https://swapi.dev/api/people/11/",
      "https://swapi.dev/api/people/16/",
      "https://swapi.dev/api/people/20/",
      "https://swapi.dev/api/people/21/",
      "https://swapi.dev/api/people/32/",
      "https://swapi.dev/api/people/33/",
      "https://swapi.dev/api/people/34/",
      "https://swapi.dev/api/people/35/",
      "https://swapi.dev/api/people/36/",
      "https://swapi.dev/api/people/37/",
      "https://swapi.dev/api/people/38/",
      "https://swapi.dev/api/people/39/",
      "https://swapi.dev/api/people/40/",
      "https://swapi.dev/api/people/41/",
      "https://swapi.dev/api/people/42/",
      "https://swapi.dev/api/people/43/",
      "https://swapi.dev/api/people/44/",
      "https://swapi.dev/api/people/46/",
      "https://swapi.dev/api/people/47/",
      "https://swapi.dev/api/people/48/",
      "https://swapi.dev/api/people/49/",
      "https://swapi.dev/api/people/50/",
      "https://swapi.dev/api/people/51/",
      "https://swapi.dev/api/people/52/",
      "https://swapi.dev/api/people/53/",
      "https://swapi.dev/api/people/54/",
      "https://swapi.dev/api/people/55/",
      "https://swapi.dev/api/people/56/",
      "https://swapi.dev/api/people/57/",
      "https://swapi.dev/api/people/58/",
      "https://swapi.dev/api/people/59/",
    ],
    planets: [
      "https://swapi.dev/api/planets/1/",
      "https://swapi.dev/api/planets/8/",
      "https://swapi.dev/api/planets/9/",
    ],
    starships: [
      "https://swapi.dev/api/starships/31/",
      "https://swapi.dev/api/starships/32/",
      "https://swapi.dev/api/starships/39/",
      "https://swapi.dev/api/starships/40/",
      "https://swapi.dev/api/starships/41/",
    ],
    vehicles: [
      "https://swapi.dev/api/vehicles/33/",
      "https://swapi.dev/api/vehicles/34/",
      "https://swapi.dev/api/vehicles/35/",
      "https://swapi.dev/api/vehicles/36/",
      "https://swapi.dev/api/vehicles/37/",
      "https://swapi.dev/api/vehicles/38/",
      "https://swapi.dev/api/vehicles/42/",
    ],
    species: [
      "https://swapi.dev/api/species/1/",
      "https://swapi.dev/api/species/2/",
      "https://swapi.dev/api/species/6/",
      "https://swapi.dev/api/species/11/",
      "https://swapi.dev/api/species/12/",
      "https://swapi.dev/api/species/13/",
      "https://swapi.dev/api/species/14/",
      "https://swapi.dev/api/species/15/",
      "https://swapi.dev/api/species/16/",
      "https://swapi.dev/api/species/17/",
      "https://swapi.dev/api/species/18/",
      "https://swapi.dev/api/species/19/",
      "https://swapi.dev/api/species/20/",
      "https://swapi.dev/api/species/21/",
      "https://swapi.dev/api/species/22/",
      "https://swapi.dev/api/species/23/",
      "https://swapi.dev/api/species/24/",
      "https://swapi.dev/api/species/25/",
      "https://swapi.dev/api/species/26/",
      "https://swapi.dev/api/species/27/",
    ],
    created: "2014-12-19T16:52:55.740000Z",
    edited: "2014-12-20T10:54:07.216000Z",
    url: "https://swapi.dev/api/films/4/",
  },
];

export const mockSpecies: Species[] = [
  {
    name: "Human",
    classification: "mammal",
    designation: "sentient",
    average_height: "180",
    skin_colors: "caucasian, black, asian, hispanic",
    hair_colors: "blonde, brown, black, red",
    eye_colors: "brown, blue, green, hazel, grey, amber",
    average_lifespan: "120",
    homeworld: "https://swapi.dev/api/planets/9/",
    language: "Galactic Basic",
    people: [
      "https://swapi.dev/api/people/66/",
      "https://swapi.dev/api/people/67/",
      "https://swapi.dev/api/people/68/",
      "https://swapi.dev/api/people/74/",
    ],
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/4/",
      "https://swapi.dev/api/films/5/",
      "https://swapi.dev/api/films/6/",
    ],
    created: "2014-12-10T13:52:11.567000Z",
    edited: "2014-12-20T21:36:42.136000Z",
    url: "https://swapi.dev/api/species/1/",
  },
  {
    name: "Droid",
    classification: "artificial",
    designation: "sentient",
    average_height: "n/a",
    skin_colors: "n/a",
    hair_colors: "n/a",
    eye_colors: "n/a",
    average_lifespan: "indefinite",
    homeworld: null,
    language: "n/a",
    people: [
      "https://swapi.dev/api/people/2/",
      "https://swapi.dev/api/people/3/",
      "https://swapi.dev/api/people/8/",
      "https://swapi.dev/api/people/23/",
    ],
    films: [
      "https://swapi.dev/api/films/1/",
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/4/",
      "https://swapi.dev/api/films/5/",
      "https://swapi.dev/api/films/6/",
    ],
    created: "2014-12-10T15:16:16.259000Z",
    edited: "2014-12-20T21:36:42.139000Z",
    url: "https://swapi.dev/api/species/2/",
  },
  {
    name: "Yoda's species",
    classification: "mammal",
    designation: "sentient",
    average_height: "66",
    skin_colors: "green, yellow",
    hair_colors: "brown, white",
    eye_colors: "brown, green, yellow",
    average_lifespan: "900",
    homeworld: "https://swapi.dev/api/planets/28/",
    language: "Galactic basic",
    people: ["https://swapi.dev/api/people/20/"],
    films: [
      "https://swapi.dev/api/films/2/",
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/4/",
      "https://swapi.dev/api/films/5/",
      "https://swapi.dev/api/films/6/",
    ],
    created: "2014-12-15T12:27:22.877000Z",
    edited: "2014-12-20T21:36:42.148000Z",
    url: "https://swapi.dev/api/species/6/",
  },
  {
    name: "Neimodian",
    classification: "unknown",
    designation: "sentient",
    average_height: "180",
    skin_colors: "grey, green",
    hair_colors: "none",
    eye_colors: "red, pink",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/18/",
    language: "Neimoidia",
    people: ["https://swapi.dev/api/people/33/"],
    films: ["https://swapi.dev/api/films/4/"],
    created: "2014-12-19T17:07:31.319000Z",
    edited: "2014-12-20T21:36:42.160000Z",
    url: "https://swapi.dev/api/species/11/",
  },
  {
    name: "Gungan",
    classification: "amphibian",
    designation: "sentient",
    average_height: "190",
    skin_colors: "brown, green",
    hair_colors: "none",
    eye_colors: "orange",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/8/",
    language: "Gungan basic",
    people: [
      "https://swapi.dev/api/people/36/",
      "https://swapi.dev/api/people/37/",
      "https://swapi.dev/api/people/38/",
    ],
    films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/5/"],
    created: "2014-12-19T17:30:37.341000Z",
    edited: "2014-12-20T21:36:42.163000Z",
    url: "https://swapi.dev/api/species/12/",
  },
  {
    name: "Toydarian",
    classification: "mammal",
    designation: "sentient",
    average_height: "120",
    skin_colors: "blue, green, grey",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "91",
    homeworld: "https://swapi.dev/api/planets/34/",
    language: "Toydarian",
    people: ["https://swapi.dev/api/people/40/"],
    films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/5/"],
    created: "2014-12-19T17:48:56.893000Z",
    edited: "2014-12-20T21:36:42.165000Z",
    url: "https://swapi.dev/api/species/13/",
  },
  {
    name: "Dug",
    classification: "mammal",
    designation: "sentient",
    average_height: "100",
    skin_colors: "brown, purple, grey, red",
    hair_colors: "none",
    eye_colors: "yellow, blue",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/35/",
    language: "Dugese",
    people: ["https://swapi.dev/api/people/41/"],
    films: ["https://swapi.dev/api/films/4/"],
    created: "2014-12-19T17:53:11.214000Z",
    edited: "2014-12-20T21:36:42.167000Z",
    url: "https://swapi.dev/api/species/14/",
  },
  {
    name: "Twi'lek",
    classification: "mammals",
    designation: "sentient",
    average_height: "200",
    skin_colors: "orange, yellow, blue, green, pink, purple, tan",
    hair_colors: "none",
    eye_colors: "blue, brown, orange, pink",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/37/",
    language: "Twi'leki",
    people: [
      "https://swapi.dev/api/people/45/",
      "https://swapi.dev/api/people/46/",
    ],
    films: [
      "https://swapi.dev/api/films/3/",
      "https://swapi.dev/api/films/4/",
      "https://swapi.dev/api/films/5/",
      "https://swapi.dev/api/films/6/",
    ],
    created: "2014-12-20T09:48:02.406000Z",
    edited: "2014-12-20T21:36:42.169000Z",
    url: "https://swapi.dev/api/species/15/",
  },
  {
    name: "Aleena",
    classification: "reptile",
    designation: "sentient",
    average_height: "80",
    skin_colors: "blue, gray",
    hair_colors: "none",
    eye_colors: "unknown",
    average_lifespan: "79",
    homeworld: "https://swapi.dev/api/planets/38/",
    language: "Aleena",
    people: ["https://swapi.dev/api/people/47/"],
    films: ["https://swapi.dev/api/films/4/"],
    created: "2014-12-20T09:53:16.481000Z",
    edited: "2014-12-20T21:36:42.171000Z",
    url: "https://swapi.dev/api/species/16/",
  },
  {
    name: "Vulptereen",
    classification: "unknown",
    designation: "sentient",
    average_height: "100",
    skin_colors: "grey",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/39/",
    language: "vulpterish",
    people: ["https://swapi.dev/api/people/48/"],
    films: ["https://swapi.dev/api/films/4/"],
    created: "2014-12-20T09:57:33.128000Z",
    edited: "2014-12-20T21:36:42.173000Z",
    url: "https://swapi.dev/api/species/17/",
  },
  {
    name: "Xexto",
    classification: "unknown",
    designation: "sentient",
    average_height: "125",
    skin_colors: "grey, yellow, purple",
    hair_colors: "none",
    eye_colors: "black",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/40/",
    language: "Xextese",
    people: ["https://swapi.dev/api/people/49/"],
    films: ["https://swapi.dev/api/films/4/"],
    created: "2014-12-20T10:02:13.915000Z",
    edited: "2014-12-20T21:36:42.175000Z",
    url: "https://swapi.dev/api/species/18/",
  },
  {
    name: "Toong",
    classification: "unknown",
    designation: "sentient",
    average_height: "200",
    skin_colors: "grey, green, yellow",
    hair_colors: "none",
    eye_colors: "orange",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/41/",
    language: "Tundan",
    people: ["https://swapi.dev/api/people/50/"],
    films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/6/"],
    created: "2014-12-20T10:08:36.795000Z",
    edited: "2014-12-20T21:36:42.177000Z",
    url: "https://swapi.dev/api/species/19/",
  },
  {
    name: "Cerean",
    classification: "mammal",
    designation: "sentient",
    average_height: "200",
    skin_colors: "pale pink",
    hair_colors: "red, blond, black, white",
    eye_colors: "hazel",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/43/",
    language: "Cerean",
    people: ["https://swapi.dev/api/people/52/"],
    films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/6/"],
    created: "2014-12-20T10:15:33.765000Z",
    edited: "2014-12-20T21:36:42.179000Z",
    url: "https://swapi.dev/api/species/20/",
  },
  {
    name: "Nautolan",
    classification: "amphibian",
    designation: "sentient",
    average_height: "180",
    skin_colors: "green, blue, brown, red",
    hair_colors: "none",
    eye_colors: "black",
    average_lifespan: "70",
    homeworld: "https://swapi.dev/api/planets/44/",
    language: "Nautila",
    people: ["https://swapi.dev/api/people/53/"],
    films: ["https://swapi.dev/api/films/4/"],
    created: "2014-12-20T10:18:58.610000Z",
    edited: "2014-12-20T21:36:42.181000Z",
    url: "https://swapi.dev/api/species/21/",
  },
  {
    name: "Zabrak",
    classification: "mammal",
    designation: "sentient",
    average_height: "180",
    skin_colors: "pale, brown, red, orange, yellow",
    hair_colors: "black",
    eye_colors: "brown, orange",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/45/",
    language: "Zabraki",
    people: [
      "https://swapi.dev/api/people/44/",
      "https://swapi.dev/api/people/54/",
    ],
    films: ["https://swapi.dev/api/films/4/"],
    created: "2014-12-20T10:26:59.894000Z",
    edited: "2014-12-20T21:36:42.183000Z",
    url: "https://swapi.dev/api/species/22/",
  },
  {
    name: "Tholothian",
    classification: "mammal",
    designation: "sentient",
    average_height: "unknown",
    skin_colors: "dark",
    hair_colors: "unknown",
    eye_colors: "blue, indigo",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/46/",
    language: "unknown",
    people: ["https://swapi.dev/api/people/55/"],
    films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/6/"],
    created: "2014-12-20T10:29:13.798000Z",
    edited: "2014-12-20T21:36:42.186000Z",
    url: "https://swapi.dev/api/species/23/",
  },
  {
    name: "Iktotchi",
    classification: "unknown",
    designation: "sentient",
    average_height: "180",
    skin_colors: "pink",
    hair_colors: "none",
    eye_colors: "orange",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/47/",
    language: "Iktotchese",
    people: ["https://swapi.dev/api/people/56/"],
    films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/6/"],
    created: "2014-12-20T10:32:13.046000Z",
    edited: "2014-12-20T21:36:42.188000Z",
    url: "https://swapi.dev/api/species/24/",
  },
  {
    name: "Quermian",
    classification: "mammal",
    designation: "sentient",
    average_height: "240",
    skin_colors: "white",
    hair_colors: "none",
    eye_colors: "yellow",
    average_lifespan: "86",
    homeworld: "https://swapi.dev/api/planets/48/",
    language: "Quermian",
    people: ["https://swapi.dev/api/people/57/"],
    films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/6/"],
    created: "2014-12-20T10:34:50.827000Z",
    edited: "2014-12-20T21:36:42.189000Z",
    url: "https://swapi.dev/api/species/25/",
  },
  {
    name: "Kel Dor",
    classification: "unknown",
    designation: "sentient",
    average_height: "180",
    skin_colors: "peach, orange, red",
    hair_colors: "none",
    eye_colors: "black, silver",
    average_lifespan: "70",
    homeworld: "https://swapi.dev/api/planets/49/",
    language: "Kel Dor",
    people: ["https://swapi.dev/api/people/58/"],
    films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/6/"],
    created: "2014-12-20T10:49:21.692000Z",
    edited: "2014-12-20T21:36:42.191000Z",
    url: "https://swapi.dev/api/species/26/",
  },
  {
    name: "Chagrian",
    classification: "amphibian",
    designation: "sentient",
    average_height: "190",
    skin_colors: "blue",
    hair_colors: "none",
    eye_colors: "blue",
    average_lifespan: "unknown",
    homeworld: "https://swapi.dev/api/planets/50/",
    language: "Chagria",
    people: ["https://swapi.dev/api/people/59/"],
    films: ["https://swapi.dev/api/films/4/", "https://swapi.dev/api/films/6/"],
    created: "2014-12-20T10:53:28.795000Z",
    edited: "2014-12-20T21:36:42.193000Z",
    url: "https://swapi.dev/api/species/27/",
  },
];
